import type {Metadata} from "next";
import "./styles/fonts"
import "./styles/globals.css";
import Providers from "@/app/providers";
import Menu from "@/components/Menu";
import ThemeRegistry from "@/app/ThemeRegistry";
import SideNavigation from "@/components/SideNavigation";
import MobileNavigationDriver from "@/components/MobileNavigationDriver"; // adjust path if needed

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body>
                <ThemeRegistry>
                    <Providers>
                        {/*<Menu/>*/}
                        <MobileNavigationDriver/>
                        <div style={{ display: 'flex', height: '100vh' }}>
                            <SideNavigation />
                            <main className="p-4" style={{ flexGrow: 1, overflowY: 'auto' }}>{children}</main>
                        </div>
                    </Providers>
                </ThemeRegistry>
            </body>
        </html>
    );
}
