import type {Metadata} from "next";
import "./styles/fonts"
import "./styles/globals.css";
import Providers from "@/app/providers";
import Menu from "@/components/Menu";
import ThemeRegistry from "@/app/ThemeRegistry"; // adjust path if needed

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body>
                <ThemeRegistry>
                    <Providers>
                        <Menu/>
                        <main className="p-4">{children}</main>
                    </Providers>
                </ThemeRegistry>
            </body>
        </html>
    );
}
